services:
  bookingservice:
    image: ghcr.io/kada-party-hb/dv1703-bookingservice:latest
    container_name: dv1703-bookingservice
    restart: unless-stopped
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
